name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "cfdevsecopsdemo" --password-stdin
        docker image build -t cfdevsecopsdemo/gitaction:latest .
        docker push cfdevsecopsdemo/gitaction:latest    
